// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcsfdbwtnkaxmpumcwyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdjc2ZkYnd0bmtheG1wdW1jd3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzEwMTMsImV4cCI6MjA2NDEwNzAxM30.U8du6TLe5NkZVyaBCSolTnna-fY4K3OAdaPVzHu12x0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);